### ISSUE TITLE
Ignore fragments option / fragments included in query object

### ISSUE THREAD

**Issue by struct78** [riot/route#98] opened 2017-06-05 02:13 UTC
It would be great if there was an option to ignore fragments/prevent fragments from triggering a route change. We aren't using a hashbang scheme for our app, but we have links that are required to go to different anchors on the page. 

For example, if I am on the main page of our app (/app/home) and click on an anchor that is supposed to scroll the user further down the page (/app/home#search), the route changes, which we don't actually want. 

Fragments are also included in the query object, which they shouldn't be.

/app/search?q=Blah&type=documents#search

Query object:
``` 
{
    'q': 'Blah',
    'type': 'documents#search'
}
```

**Comment by GianlucaGuarini** [comment] 2017-06-07 16:04
@struct78 there is already a javascript api for this feature https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams why should the riot router provide a non standard way of doing it?

**Comment by struct78** [comment] 2017-06-14 01:55
@GianlucaGuarini Not sure how that's relevant to my query? What I'm asking is, is it possible to include an option that prevents riot route from triggering a route change when a URL fragment is added or changed. I don't particularly care about fragments being included in the query object

**Comment by GianlucaGuarini** [comment] 2017-06-14 06:21
@struct78 ah ok sorry I got it wrong :)

**Comment by cognitom** [comment] 2017-06-14 08:37
@struct78 the `route.query()` was designed to handle a url like this:

```
/app/search#search?q=Blah&type=documents
```

not like this:

```
/app/search?q=Blah&type=documents#search
```

But it should be able to handle the latter one, I think. We can simply change the RegExp on this line:
https://github.com/riot/route/blob/f1bd42223963f9170cfd60045ca5824cb0f0f17f/src/index.js#L305

**Comment by GianlucaGuarini** [comment] 2019-11-23 19:41
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.

**Closed by GianlucaGuarini** 2019-11-23 19:41 UTC
