### ISSUE TITLE
Remove /

### ISSUE THREAD

**Issue by pfrlv** [riot/route#78] opened 2016-12-07 22:46 UTC
Hi,
i have a `route.base('/translations)`
and when i click on link with `href="/translations/login"` my url becoming _/translationslogin_.
How i can create _translations/login_?

**Comment by cognitom** [comment] 2016-12-08 00:57
That seems strange...
I couldn't reproduce it. Could you show the minimal example? HTML and tag files.

**Comment by pfrlv** [comment] 2016-12-08 06:48
`route.base('/translators')`
```javascript
<div if={ !is_login } >
      <a href="/translators/login">Log in</a>
</div>
```

And after click i have https://lingviny.com/translatorslogin

**Comment by cognitom** [comment] 2016-12-08 07:13
I need entire code to understand your situation...
Can you try to open this link, and create an example?
http://riotjs.com/examples/plunker/?app=bug-reporter

I know plunker doesn't support routing for history API, so you don't have to make it perfect.

**Comment by pfrlv** [comment] 2016-12-08 07:29
@cognitom http://run.plnkr.co/j0Jg1hVH8NkHYuuj/
Hmmmm....

**Comment by pfrlv** [comment] 2016-12-08 08:07
@cognitom i do not want to rush to answer, but what is it?

**Comment by cognitom** [comment] 2016-12-11 09:49
@pfrlv, gotcha. We might need normalization for `base()`.
Temporary solution is here:

```javascript
route.base('/translators/');
```

I'll write the fix soon.

**Comment by no-wa-ke** [comment] 2017-04-03 14:36
@cognitom that does not seem to work when you access without slash(/)...

http://plnkr.co/edit/meCJYbnkthLDwmGEf6U9

with slash:
http://run.plnkr.co/HMDQNXbfOieYXo3v/

wo slash:
http://run.plnkr.co/HMDQNXbfOieYXo3v

is this expected behavior?

**Comment by GianlucaGuarini** [comment] 2019-11-23 19:42
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.

**Closed by GianlucaGuarini** 2019-11-23 19:42 UTC
Labels: bug
