### ISSUE TITLE
Updating component on route change

### ISSUE THREAD

**Issue by jfbrennan** [riot/route#171] opened 2023-07-14 23:59 UTC
It's not clear if this is possible, but I am trying to get a component to update when the route changes:
```html
<route-hoc path="/home/students/:slug">
  <hs-student slug="{route.params.slug}"></hs-student>
</route-hoc>
```
I expected the `hs-student` component to update when `slug` changed, but it doesn't. In the initial render its `props.slug` is set as expected, but after that nothing seems to be able to trigger an update. In fact, I don't see how it's even possible to watch that route for changes and `this.update()` here in the parent component to trigger it either.

Am I missing something or am hitting a limitation of the Riot router?

**Comment by GianlucaGuarini** [comment] 2023-07-15 20:11
Thank you for your issue. Your example should work [see our demo](https://plnkr.co/edit/?p=preview&preview).
Please try to reproduce this bug in a code example I can debug. I will be glad to see how to reproduce this issue

**Comment by GianlucaGuarini** [comment] 2023-07-18 06:36
I am unable to reproduce the issue https://plnkr.co/edit/BadOsvcZFTa4cHA3

**Comment by GianlucaGuarini** [comment] 2023-07-21 20:51
closing this issue due to the lack of a reproducible example. I will be glad to re-open it when it will be eventually provided.

**Closed by GianlucaGuarini** 2023-07-21 20:51 UTC
Labels: invalid
