### ISSUE TITLE
IE 10 routing issue on load

### ISSUE THREAD

**Issue by DeltaV93** [riot/route#118] opened 2018-05-04 17:39 UTC
I was testing in IE 10 by using the emulation tab in IE 11, I found that routing is not working on initial load. 

If I land on http://localhost:8080/login the page loads the top nav and footer, but does not load the main view. 

But when I land on  http://localhost:8080/  and click the logo that has an href of http://localhost:8080/login the main view loads correctly and I can navigate around the app. But if I refresh the page I get the same issue. 

When testing in all other browsers everything looks fine, it only breaks with IE 10. I'm not sure if this is an issue with the way I have my webpack or if it's the way I'm using the router, but I've attached my code in the link [Here](http://embed.plnkr.co/RurZ6RMnL6iMWqkvyZhB/).

**Comment by AndersonBargas** [comment] 2018-07-06 21:13
Hello @DeltaV93 . I tried (almost the same code) on IE10 and everything went well. Maybe because i can´t exactly reproduce your setup (the files you uploaded isn´t enough to run your entire system).

Have you solved the problem or are you still experiencing difficulties?

**Comment by DeltaV93** [comment] 2018-07-10 16:15
@AndersonBargas  Hi thanks for trying to help. I was not able to get this working in IE. I'm going to set up a repo with all of the project files for you to test.

**Comment by GianlucaGuarini** [comment] 2019-11-23 19:39
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.

**Closed by GianlucaGuarini** 2019-11-23 19:39 UTC
Labels: question
