### ISSUE TITLE
Cannot pass options to routed tags

### ISSUE THREAD

**Issue by PascalLeMerrer** [riot/route#84] opened 2017-02-01 20:55 UTC
Hello

I created a basic app with Riot 3.1.0, and the latest router (I built it from sources, as riot+route.min.js doesn't seem to be available on jsdelivr).

The app contains three files:

hello.tag:

```html
<hello>
  <span>Hello { opts.name }!</span>
</hello>
```

app.tag:

```html
<app>
    <router>
      <route path="">
        <hello name={ name }></hello>
      </route>
    </router>
    <script>
        this.name = "World"
    </script>
</app>
```

index.html:

```html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>

    <app></app>

    <script type="text/javascript" src="riot+compiler.min.js"></script>
    <script src="route+tag.min.js"></script>
    <script type="riot/tag" data-src="./app.tag"></script>
    <script type="riot/tag" data-src="./hello.tag"></script>

    <script type="text/javascript">
      riot.mount('app')
    </script>

  </body>
</html>
```
I expected this to display "Hello World!" but the result is "Hello!".
In hello.tag, this.opts.name is an empty string.

Did I miss something, or is there a real problem?

**Comment by cognitom** [comment] 2017-02-02 17:24
@PascalLeMerrer maybe `<hello name={ parent.parent.name }></hello>`?

**Comment by PascalLeMerrer** [comment] 2017-02-03 07:39
It dos not work. And even if it had, it wouldnt have been elegant. And I love Riot because it's elegant.

**Comment by GianlucaGuarini** [comment] 2017-02-03 07:51
@PascalLeMerrer is right we would need a better solution. The problem is that the `yield` directive in riot still sucks a bit, I would probably propose to use for now a custom solution. We will fix the yield issue in the next releases

**Comment by PascalLeMerrer** [comment] 2017-02-03 08:58
By now I will use a solution based on the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)

**Comment by cognitom** [comment] 2017-02-03 12:40
@PascalLeMerrer agreed. I'm not the big fan of `parent.parent.`, too.

BTW, it works in a not-elegant way, at least. Check this plunker.
http://plnkr.co/edit/FveBDxSRTWrfwPrl6NEF?p=preview

**Comment by PascalLeMerrer** [comment] 2017-02-04 08:32
My bad! I probably forgot to save my file when I tested. Thanks @cognitom

**Comment by AndersonBargas** [comment] 2018-07-05 23:03
Hello @PascalLeMerrer. I made a experiment that looks more elegant, since it´s don´t uses the parent reference.
Please, give a look at http://plnkr.co/edit/edr8ep?p=preview

**Comment by PascalLeMerrer** [comment] 2018-07-06 18:47
It's nicer indeed. Thx @AndersonBargas 👍

**Comment by GianlucaGuarini** [comment] 2019-11-23 19:41
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.

**Closed by GianlucaGuarini** 2019-11-23 19:41 UTC
Labels: question
