### ISSUE TITLE
ReferenceError: Can't find variable: central with riot 3.0.1

### ISSUE THREAD

**Issue by weberan** [riot/route#76] opened 2016-11-30 21:49 UTC
I updated from riot 2.x to 3.01 and I am using webpack:

> Router — cjs.route.js:97 ReferenceError: Can't find variable: central

Any idea?

**Comment by cognitom** [comment] 2016-12-01 02:50
@weberan `riot-observable` seems not installed, or webpack couldn't find it in your dependency tree.

`central` is a central observer in `riot-route`
https://github.com/riot/route/blob/v3.0.1/dist/cjs.route.js#L27

**Comment by weberan** [comment] 2016-12-01 21:12
@cognitom I thought riot-observable was installed by installing riot itself. I added it to my setup, I upgraded webpack, babel and everything: still the same problem.

Loading the stuff also works well:
>    [54] ./~/riot-observable/dist/observable.js 3.17 kB {0} [built]
>   [55] ./~/riot-route/dist/cjs.route.js 9.12 kB {0} [built]

> central is a central observer in riot-route

checked that already, looks fine for me.

**Comment by cognitom** [comment] 2016-12-02 01:08
@weberan could you show your setup, or a minimum repo for reproduce it?

**Comment by GianlucaGuarini** [comment] 2019-11-23 19:42
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.

**Closed by GianlucaGuarini** 2019-11-23 19:42 UTC
